// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGYd43tCNuWoNDq22whP2RTmUz_-6IbGo',
    appId: '1:207300010397:web:13acebca0982da2b294f74',
    messagingSenderId: '207300010397',
    projectId: 'entredos-46d91',
    authDomain: 'entredos-46d91.firebaseapp.com',
    storageBucket: 'entredos-46d91.firebasestorage.app',
    measurementId: 'G-FCV0RSCRNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe-4a-6F-HZntCai1vobqE6HRVTqScNyE',
    appId: '1:207300010397:android:3df028fd40c2ac72294f74',
    messagingSenderId: '207300010397',
    projectId: 'entredos-46d91',
    storageBucket: 'entredos-46d91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKC1CwO-VGBcvuuLJb7g1pdW6Y2cj--EE',
    appId: '1:207300010397:ios:09138e97e5aabf08294f74',
    messagingSenderId: '207300010397',
    projectId: 'entredos-46d91',
    storageBucket: 'entredos-46d91.firebasestorage.app',
    androidClientId: '207300010397-l8t7a7saffrpcqtf99dpbgeeelndcjv9.apps.googleusercontent.com',
    iosClientId: '207300010397-5e3uva8punoamt645ngoliqcbg0i7qke.apps.googleusercontent.com',
    iosBundleId: 'com.example.entredos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKC1CwO-VGBcvuuLJb7g1pdW6Y2cj--EE',
    appId: '1:207300010397:ios:09138e97e5aabf08294f74',
    messagingSenderId: '207300010397',
    projectId: 'entredos-46d91',
    storageBucket: 'entredos-46d91.firebasestorage.app',
    androidClientId: '207300010397-l8t7a7saffrpcqtf99dpbgeeelndcjv9.apps.googleusercontent.com',
    iosClientId: '207300010397-5e3uva8punoamt645ngoliqcbg0i7qke.apps.googleusercontent.com',
    iosBundleId: 'com.example.entredos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGYd43tCNuWoNDq22whP2RTmUz_-6IbGo',
    appId: '1:207300010397:web:e16cf7a5a2652034294f74',
    messagingSenderId: '207300010397',
    projectId: 'entredos-46d91',
    authDomain: 'entredos-46d91.firebaseapp.com',
    storageBucket: 'entredos-46d91.firebasestorage.app',
    measurementId: 'G-FV7YXQD7N8',
  );

}